apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: fitcoach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main
          image: csborges/main-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-main
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-main
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-main
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-main
                  key: SPRING_DATASOURCE_PASSWORD

            - name: WORKOUT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-main
                  key: WORKOUT_SERVICE_URL

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-main
                  key: RABBITMQ_HOST

            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-main
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-main
                  key: RABBITMQ_PASS

          livenessProbe:
            httpGet:
              path: /actuator/health/liviness
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 5
