apiVersion: v1
kind: Secret
metadata:
  name: secret-main
  namespace: fitcoach
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=     # postgres
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=         # admin
  RABBITMQ_USER: Z3Vlc3Q=                      # guest
  RABBITMQ_PASS: Z3Vlc3Q=                      # guest
