apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
  namespace: fitcoach
  labels:
    app: workout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workout-service
  template:
    metadata:
      labels:
        app: workout-service
    spec:
      containers:
        - name: workout-service
          image: csborges/workout-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: workout-config
            - secretRef:
                name: workout-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: fitcoach
spec:
  selector:
    app: workout-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: None
